theme: jekyll-theme-minimal
baseurl: /
logo: https://raw.githubusercontent.com/luiscastilho/dungeoneering/main/docs/images/logos/dungeoneering-logo-black-v1.png
title: dungeoneering
description: Minimalistic virtual tabletop (VTT) for local, in-person RPG sessions
show_downloads: "true"
markdown: kramdown