theme: jekyll-theme-minimal
baseurl: /
logo: https://raw.githubusercontent.com/luiscastilho/dungeoneering/main/docs/images/logos/dungeoneering-logo-black-v1.png
title: dungeoneering
description: Minimalistic virtual tabletop (VTT) for local, in-person RPG sessions
image: https://raw.githubusercontent.com/luiscastilho/dungeoneering/main/docs/images/social/cover-1200x627.png
show_downloads: "true"
markdown: kramdown
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap